### PR TITLE
Modest updates to Readme.md

### PR DESCRIPTION
**Pull request by Jerimee**
This pr is a baby step; it does only two things: correct a minor spelling typo in english and update readme.md

It is a branch based on *develop* NOT MASTER branch

### CODE REVIEW

**Comment by Jerimee** [comment]
note 4 commits

**Comment by octfx** [comment]
Thank you very much for your contribution! 

One general note: Could you split the readme changes and addition of a service into two separate pull request? 
This way everything is clean and separated

**Comment by Jerimee** [comment]
Will do

**Comment by Jerimee** [comment]
ok this is now just README and small typo

**Comment by octfx** [comment]
Merged.

Thanks again for the readme updates!

**Pull request merged**
